version: '3'

services:
    php:
        container_name: php
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./php/:/var/www/html/
        networks:
            - person

    db:
        container_name: database
        image: mysql:8.0.29
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: person
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - person

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.2.0
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=db
        networks:
            - person

volumes:
    db-data:

networks:
    person:
